### ISSUE TITLE
Relicense as dual Apache / BSD 2 clause

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging#42]
Similarly to what pyca/cryptography did, let's relicense as dual Apache License 2.0 and BSD 2 clause. This will allow folks with GPLv2 codebases to use packaging while still retaining the additional protections of Apache License 2.0. More information can be found in pyca/cryptography#1209. If you're one of the people who have contributed, please respond to this issue stating whether or not you give permission for your code to be relicensed as dual Apache License 2.0 and 2 clause BSD.

####  Tasks

* [ ] Update ``LICENSE`` file appropriately.
* [ ] Update ``setup.py`` classifiers.
* [ ] Update ``__about__.py``.
* [ ] Figure out what to do with copyright headers in every file.
* [ ] Update contributing documentation
* [ ] Receive consent of all folks who have contributed to packaging in the past.
* [ ] Changelog entry.

#### List of folks whose consent we need

* [x] Donald Stufft (@dstufft)
* [x] Vincent Driessen (@nvie)
* [x] Paul Moore (@pfmoore)
* [x] Xavier Fernandez (@xavfernandez)
* [x] Ian Cordasco (@sigmavirus24)
* [x] Marc Abramowitz (@msabramo)

**Comment by dstufft** [comment]
I give my permission.

**Comment by sigmavirus24** [comment]
I give my permission.

**Comment by pfmoore** [comment]
I give my permission.

**Comment by nvie** [comment]
I give my permission.

**Comment by njsmith** [comment]
There's a comment in version.py that seems to imply that it contains code copied from setuptools? That complicates relicensing if true.

**Comment by pfmoore** [comment]
The comment says the "scheme" is copied, which I understood to mean the specification of how the version is mapped, rather than the code itself. But if it's a problem, then if someone wants to write up a spec for me I'll reimplement it if that helps - I've never looked at the setuptools code so that should count as an independent implementation...

**Comment by dstufft** [comment]
If I recall, there was about 10 lines of code adapted from the setuptools implementation. I think it's arguable that those 10 lines are not novel and are the obvious way of implementing the algorithm. I can check with an IP lawyer though.

**Comment by sfriesel** [comment]
FYI this seems to be the original commit in setuptools https://github.com/jaraco/setuptools/commit/1a7cff662b734fed26360983b961ce70b889767e
(according to that git clone of an hg repository that was imported from cvs)

**Comment by dstufft** [comment]
I sent an email to a someone I know who is an IP lawyer, we'll see if he responds and what he says.

**Comment by xavfernandez** [comment]
I give my permission.

**Comment by njsmith** [comment]
@dstufft: do you know which lines are the ones copied from setuptools? I'm wondering specifically because I'm hoping that they're restricted to the `LegacyVersion` code paths, and for my immediate purposes I could just rip those out :-)

**Comment by dstufft** [comment]
@njsmith Yes. It's https://github.com/pypa/packaging/blob/225cfabeaaff0590021aab492b8f0bd2d6109d9d/packaging/version.py#L115-L165

**Comment by msabramo** [comment]
I give my permission

**Comment by dstufft** [comment]
Ok great. That's everyone's permission. The only items left are code changes, and figuring out the deal with little bit of code I copied from setuptools. I might just email PJE to see if I can get his permission to license it as Apache and 2 clause BSD.

**Comment by dstufft** [comment]
Ok. I reached out to PJ Elby and he gave me permission via email to license that bit of code Apache License 2.0 and 2 clause BSD. So that should resolve all the legal issues here, and we can just do the source changes.
